// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mV6bTXul5W4zj0PuA126xbSm9X43dQU',
    appId: '1:435696584216:web:349bef834c7ced7c12656d',
    messagingSenderId: '435696584216',
    projectId: 'safedrive-f52ba',
    authDomain: 'safedrive-f52ba.firebaseapp.com',
    storageBucket: 'safedrive-f52ba.firebasestorage.app',
    measurementId: 'G-D5W01ZWQXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHzDcEKdjNNX14eACPRZIwli7wk_HrsPk',
    appId: '1:435696584216:android:9b5bd41c62a01a8212656d',
    messagingSenderId: '435696584216',
    projectId: 'safedrive-f52ba',
    storageBucket: 'safedrive-f52ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbh75rxM5OcBoCa4U21Lk_n0EL3Ou3hf8',
    appId: '1:435696584216:ios:c35cfa077826ad8712656d',
    messagingSenderId: '435696584216',
    projectId: 'safedrive-f52ba',
    storageBucket: 'safedrive-f52ba.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbh75rxM5OcBoCa4U21Lk_n0EL3Ou3hf8',
    appId: '1:435696584216:ios:c35cfa077826ad8712656d',
    messagingSenderId: '435696584216',
    projectId: 'safedrive-f52ba',
    storageBucket: 'safedrive-f52ba.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mV6bTXul5W4zj0PuA126xbSm9X43dQU',
    appId: '1:435696584216:web:fb0db92bbf6bb26d12656d',
    messagingSenderId: '435696584216',
    projectId: 'safedrive-f52ba',
    authDomain: 'safedrive-f52ba.firebaseapp.com',
    storageBucket: 'safedrive-f52ba.firebasestorage.app',
    measurementId: 'G-H6LB0F90WD',
  );
}
